### ISSUE TITLE
Error when saving diagnostic info

### ISSUE THREAD

**Issue by timmens** [numericalalgorithmsgroup/dfols#23]
Hello!

I am having trouble saving diagnostic info with the most recent version of DFO-LS (1.5.1, installed from PyPI). I am unsure whether I am using the feature incorrectly, or whether this is a DFO-LS bug.

### Minimal Reproducible Example

```python
import dfols
import numpy as np

def objfun(x):
    return x

x0 = np.arange(3)

results = dfols.solve(
    objfun=objfun,
    x0=x0,
    user_params={"logging.save_diagnostic_info": True},
)
```

### Error

```console
Traceback (most recent call last):
  File "/home/dfols-test/src/dfols_test/dfols_test.py", line 10, in <module>
    results = dfols.solve(
        objfun=objfun,
    ...<2 lines>...
        user_params={"logging.save_diagnostic_info": True},
    )
  File "/home/dfols-test/.pixi/envs/v151/lib/python3.13/site-packages/dfols/solver.py", line 1065, in solve
    solve_main(objfun, x0, argsf, xl, xu, projections, npt, rhobeg, rhoend, maxfun, nruns, nf, nx, nsamples, params,
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                diagnostic_info, scaling_changes, h, lh, argsh, prox_uh, argsprox, default_growing_method_set_by_user=default_growing_method_set_by_user,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
               do_logging=do_logging, print_progress=print_progress)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dfols-test/.pixi/envs/v151/lib/python3.13/site-packages/dfols/solver.py", line 309, in solve_main
    diagnostic_info.save_info_from_control(control, nruns_so_far, current_iter,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                           save_poisedness=params("logging.save_poisedness"))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dfols-test/.pixi/envs/v151/lib/python3.13/site-packages/dfols/diagnostic_info.py", line 105, in save_info_from_control
    x, rvec, f, jac, nsamples = control.model.get_final_results()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 5)
```

### Some Info

- Python=3.11
- The code does **not** throw any errors with DFO-LS version 1.5.0
- The code does **not** throw any errors if `user_params={"logging.save_diagnostic_info": False}`

Please let me know if you need any further information. Thank you!

**Comment by lindonroberts** [comment]
Thanks, you're right that this was a bug introduced in v1.5.1. I have just released v1.5.2 which fixes this issue.
