### ISSUE TITLE
Solver fails when using integer-valued x0

### ISSUE THREAD

**Issue by tinosulzer** [numericalalgorithmsgroup/dfols#9]
Hey @lindonroberts , don't know if you're still maintaining this / looking for bug reports, but the solver fails if you give it integer-valued initial conditions. Adapting the simple example and just changing `x0`:
```python3
# DFO-LS example: minimize the Rosenbrock function
from __future__ import print_function
import numpy as np
import dfols

# Define the objective function
def rosenbrock(x):
    return np.array([10.0 * (x[1] - x[0] ** 2), 1.0 - x[0]])


# Define the starting point
x0 = np.array([-1, 1])

# Set random seed (for reproducibility)
np.random.seed(0)

# Call DFO-LS
soln = dfols.solve(rosenbrock, x0)

# Display output
print(soln)
```
gives the error
```
Traceback (most recent call last):
  File "dfols_example.py", line 18, in <module>
    soln = dfols.solve(rosenbrock, x0)
  File "/mnt/c/Users/vsulzer/Documents/Energy_Storage/toyota_1d_pemfc/Toyota/lib/python3.6/site-packages/dfols/solver.py", line 967, in solve
    diagnostic_info, scaling_changes, default_growing_method_set_by_user=default_growing_method_set_by_user)
  File "/mnt/c/Users/vsulzer/Documents/Energy_Storage/toyota_1d_pemfc/Toyota/lib/python3.6/site-packages/dfols/solver.py", line 741, in solve_main
    did_fix_geom, exit_info = control.check_and_fix_geometry(distsq, update_delta, number_of_samples, params)
  File "/mnt/c/Users/vsulzer/Documents/Energy_Storage/toyota_1d_pemfc/Toyota/lib/python3.6/site-packages/dfols/controller.py", line 387, in check_and_fix_geometry
    self.model.shift_base(self.model.xopt())
  File "/mnt/c/Users/vsulzer/Documents/Energy_Storage/toyota_1d_pemfc/Toyota/lib/python3.6/site-packages/dfols/model.py", line 258, in shift_base
    self.xbase += xbase_shift
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

**Comment by tinosulzer** [comment]
Great! Easy enough to avoid by passing the right initial conditions, just thought I'd let you know :)
